#!/bin/sh
#
# Start the wifi connection....
#

case "$1" in
  start)
 	echo "Starting wifi..."
	/sbin/network.sh start
        echo "Starting to monitor wifi connection..."
        /sbin/network.sh monitor &>/var/log/wifi.log
	;;
  stop)
	echo -n "Stopping wifi..."
	killall -p network.sh
	;;
  restart|restart)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

