#!/bin/sh

# Sanity checks
DAEMON=`which LCDd`
test -x ${DAEMON} || exit 0
test -f /etc/lcdproc.conf || exit 0

start() {
	echo -n "Starting lcdproc: "
	start-stop-daemon --start --quiet --background --exec ${DAEMON} \
		&& echo "OK" || echo "FAIL"
}

stop() {
	echo -n "Stopping lcdproc: "
	start-stop-daemon --stop --quiet --exec ${DAEMON} \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

