#!/bin/sh

# Sanity checks
DAEMON=`which mpdlcd`
test -x ${DAEMON} || exit 0
test -f /etc/mpdlcd.conf || exit 0

DAEMON_OPTS="  --syslog"

start() {
	echo -n "Starting mpdlcd: "
	start-stop-daemon --start --quiet --background --exec ${DAEMON} -- ${DAEMON_OPTS} \
		&& echo "OK" || echo "FAIL"
}

stop() {
	echo -n "Stopping mpdlcd: "
	start-stop-daemon --stop --quiet --exec ${DAEMON} \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

